/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Host.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { axiosInstance } from "../mutator/axios-instance";
import type { ErrorType, BodyType } from "../mutator/axios-instance";
export type PutApiV1Communities500 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type PutApiV1Communities400 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type PostApiV1Communities500 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type PostApiV1Communities400 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type GetApiV1Communities500 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type GetApiV1Communities400 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export type GetApiV1CommunitiesParams = {
  pageIndex: number;
  pageSize: number;
  name?: string;
};

export type GetApiV1UsersMe500 = {
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
  /** @nullable */
  status?: number | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  type?: string | null;
};

export interface UsersQueriesGetUserByExternalIdResponse {
  id: string;
}

export interface CommunitiesQueriesGetCommunitiesDto {
  id: string;
  name: string;
  ownerId: string;
}

export interface CommunitiesQueriesGetCommunitiesResponse {
  communities: CommunitiesQueriesGetCommunitiesDto[];
  total: number;
}

export interface CommunitiesCommandsEditCommunityCommand {
  id: string;
  name: string;
}

export interface CommunitiesCommandsAddCommunityCommand {
  id: string;
  name: string;
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

export const getApiV1UsersMe = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<UsersQueriesGetUserByExternalIdResponse>(
    { url: `/api/v1/users/me`, method: "GET", signal },
    options,
  );
};

export const getGetApiV1UsersMeQueryKey = () => {
  return [`/api/v1/users/me`] as const;
};

export const getGetApiV1UsersMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1UsersMe>>,
  TError = ErrorType<void | GetApiV1UsersMe500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiV1UsersMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV1UsersMe>>> = ({
    signal,
  }) => getApiV1UsersMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1UsersMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetApiV1UsersMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1UsersMe>>
>;
export type GetApiV1UsersMeQueryError = ErrorType<void | GetApiV1UsersMe500>;

export function useGetApiV1UsersMe<
  TData = Awaited<ReturnType<typeof getApiV1UsersMe>>,
  TError = ErrorType<void | GetApiV1UsersMe500>,
>(options: {
  query: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getApiV1UsersMe>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof axiosInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetApiV1UsersMe<
  TData = Awaited<ReturnType<typeof getApiV1UsersMe>>,
  TError = ErrorType<void | GetApiV1UsersMe500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getApiV1UsersMe>>,
        TError,
        TData
      >,
      "initialData"
    >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApiV1UsersMe<
  TData = Awaited<ReturnType<typeof getApiV1UsersMe>>,
  TError = ErrorType<void | GetApiV1UsersMe500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useGetApiV1UsersMe<
  TData = Awaited<ReturnType<typeof getApiV1UsersMe>>,
  TError = ErrorType<void | GetApiV1UsersMe500>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiV1UsersMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetApiV1UsersMeQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getApiV1Communities = (
  params: GetApiV1CommunitiesParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CommunitiesQueriesGetCommunitiesResponse>(
    { url: `/api/v1/communities`, method: "GET", params, signal },
    options,
  );
};

export const getGetApiV1CommunitiesQueryKey = (
  params: GetApiV1CommunitiesParams,
) => {
  return [`/api/v1/communities`, ...(params ? [params] : [])] as const;
};

export const getGetApiV1CommunitiesQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiV1Communities>>,
  TError = ErrorType<GetApiV1Communities400 | GetApiV1Communities500>,
>(
  params: GetApiV1CommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Communities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiV1CommunitiesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiV1Communities>>
  > = ({ signal }) => getApiV1Communities(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiV1Communities>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type GetApiV1CommunitiesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiV1Communities>>
>;
export type GetApiV1CommunitiesQueryError = ErrorType<
  GetApiV1Communities400 | GetApiV1Communities500
>;

export function useGetApiV1Communities<
  TData = Awaited<ReturnType<typeof getApiV1Communities>>,
  TError = ErrorType<GetApiV1Communities400 | GetApiV1Communities500>,
>(
  params: GetApiV1CommunitiesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Communities>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Communities>>,
          TError,
          TData
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useGetApiV1Communities<
  TData = Awaited<ReturnType<typeof getApiV1Communities>>,
  TError = ErrorType<GetApiV1Communities400 | GetApiV1Communities500>,
>(
  params: GetApiV1CommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Communities>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV1Communities>>,
          TError,
          TData
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useGetApiV1Communities<
  TData = Awaited<ReturnType<typeof getApiV1Communities>>,
  TError = ErrorType<GetApiV1Communities400 | GetApiV1Communities500>,
>(
  params: GetApiV1CommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Communities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useGetApiV1Communities<
  TData = Awaited<ReturnType<typeof getApiV1Communities>>,
  TError = ErrorType<GetApiV1Communities400 | GetApiV1Communities500>,
>(
  params: GetApiV1CommunitiesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiV1Communities>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getGetApiV1CommunitiesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postApiV1Communities = (
  communitiesCommandsAddCommunityCommand: BodyType<CommunitiesCommandsAddCommunityCommand>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<void>(
    {
      url: `/api/v1/communities`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: communitiesCommandsAddCommunityCommand,
      signal,
    },
    options,
  );
};

export const getPostApiV1CommunitiesMutationOptions = <
  TError = ErrorType<PostApiV1Communities400 | void | PostApiV1Communities500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Communities>>,
    TError,
    { data: BodyType<CommunitiesCommandsAddCommunityCommand> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiV1Communities>>,
  TError,
  { data: BodyType<CommunitiesCommandsAddCommunityCommand> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiV1Communities>>,
    { data: BodyType<CommunitiesCommandsAddCommunityCommand> }
  > = (props) => {
    const { data } = props ?? {};

    return postApiV1Communities(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiV1CommunitiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiV1Communities>>
>;
export type PostApiV1CommunitiesMutationBody =
  BodyType<CommunitiesCommandsAddCommunityCommand>;
export type PostApiV1CommunitiesMutationError = ErrorType<
  PostApiV1Communities400 | void | PostApiV1Communities500
>;

export const usePostApiV1Communities = <
  TError = ErrorType<PostApiV1Communities400 | void | PostApiV1Communities500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiV1Communities>>,
    TError,
    { data: BodyType<CommunitiesCommandsAddCommunityCommand> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof postApiV1Communities>>,
  TError,
  { data: BodyType<CommunitiesCommandsAddCommunityCommand> },
  TContext
> => {
  const mutationOptions = getPostApiV1CommunitiesMutationOptions(options);

  return useMutation(mutationOptions);
};

export const putApiV1Communities = (
  communitiesCommandsEditCommunityCommand: BodyType<CommunitiesCommandsEditCommunityCommand>,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<void>(
    {
      url: `/api/v1/communities`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: communitiesCommandsEditCommunityCommand,
    },
    options,
  );
};

export const getPutApiV1CommunitiesMutationOptions = <
  TError = ErrorType<PutApiV1Communities400 | void | PutApiV1Communities500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1Communities>>,
    TError,
    { data: BodyType<CommunitiesCommandsEditCommunityCommand> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiV1Communities>>,
  TError,
  { data: BodyType<CommunitiesCommandsEditCommunityCommand> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiV1Communities>>,
    { data: BodyType<CommunitiesCommandsEditCommunityCommand> }
  > = (props) => {
    const { data } = props ?? {};

    return putApiV1Communities(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiV1CommunitiesMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiV1Communities>>
>;
export type PutApiV1CommunitiesMutationBody =
  BodyType<CommunitiesCommandsEditCommunityCommand>;
export type PutApiV1CommunitiesMutationError = ErrorType<
  PutApiV1Communities400 | void | PutApiV1Communities500
>;

export const usePutApiV1Communities = <
  TError = ErrorType<PutApiV1Communities400 | void | PutApiV1Communities500>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiV1Communities>>,
    TError,
    { data: BodyType<CommunitiesCommandsEditCommunityCommand> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationResult<
  Awaited<ReturnType<typeof putApiV1Communities>>,
  TError,
  { data: BodyType<CommunitiesCommandsEditCommunityCommand> },
  TContext
> => {
  const mutationOptions = getPutApiV1CommunitiesMutationOptions(options);

  return useMutation(mutationOptions);
};
